#!/usr/bin/env sh

watch -t -c -n 0.3 git log --graph --color --all --abbrev-commit --decorate --format=format:'"%C(bold blue)%h%C(reset) - %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)"'
