#!/usr/bin/env bash

source ./scripts/git

COMMIT_ID=$(( COMMIT_ID + 1 ))
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

touch src/file_${COMMIT_ID}.js
add_file src/file_${COMMIT_ID}.js
add_file_content src/file_${COMMIT_ID}.js ${COMMIT_ID}
commit_file src/file_${COMMIT_ID}.js "feat: add file_${COMMIT_ID}"

set_commit_id ${COMMIT_ID}
