#!/bin/bash

source ./scripts/git

module=${1}

switch_to_branch "tutorial"

osascript<<EOF
    tell application "iTerm"
        activate
        select first window

        # Create new tab
        tell current window
            create tab with default profile
        end tell

        # Split horizontally
        tell current session of current window
            split horizontally with default profile
            split horizontally with default profile
        end tell

        # Split top tab vertically
        tell first session of current tab of current window
            split vertically with default profile
        end tell

        # Run command in Pane (top-left)
        tell first session of current tab of current window
            write text "cd ~/perso/gitutor/"
            write text "./scripts/watch/status"
        end tell

        # Run command in Pane (top-right)
        tell second session of current tab of current window
            write text "cd ~/perso/gitutor/"
            write text "./scripts/watch/graph"
        end tell

        # Run command in Pane (middle)
        tell third session of current tab of current window
            write text "cd ~/perso/gitutor/"
        end tell

        # Run command in Pane (bottom)
        tell fourth session of current tab of current window
            write text "cd ~/perso/gitutor/"
            write text "./scripts/watch/steps ${module}"
        end tell
    end tell
EOF
